### ISSUE TITLE
deployできない

### ISSUE THREAD

**Issue by yuji5818** [yusuke-konishi/dive23#69]
-アセットコンパイルが正しくできていない可能性がある

--------------------------------------------------- 
      Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
---------------------------------------------------

**Comment by yusuke-konishi** [comment]
以下の PR で対応しました。

https://github.com/yusuke-konishi/dive23/pull/71

**Comment by yuji5818** [comment]
ご対応ありがとうございます！
